name: Flutter Weekly Windows Build

on:
  schedule:
    # schedule build every week
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  run-flutter-weekly-build:
    uses: ./.github/workflows/flutter-build-w.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "Windows"
