name: Flutter Weekly Mobile Build

on:
  schedule:
    # schedule build every week
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  run-flutter-weekly-build:
    uses: ./.github/workflows/flutter-build-a.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "Mobile"
